Add-remove Tasks
Ofarouq310/Todo-list-app pull request #2
Opened 2022-11-05 21:12 UTC by Ofarouq310

## Summary of branch additions: 
- [x] Implement a function for adding and deleting a task.
- [x] Implement a function for editing task descriptions.
- [x] "Completed" property is set to false by default.
- [x] Updating tasks indexes upon deleting tasks.

2022-11-05 21:46 UTC, gemmen29 requested changes
Hi @Ofarouq310, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 21:46 UTC, gemmen29 commented on src/modules/addDeleteTask.js
> +  editTask();
- [ ] Kindly fix the `edit` task functionality by updating the local storage when you edit any task as now when I press the edit button then enter a new value for a task and try to refresh the page the task remains the same as the old state.

2022-11-05 22:48 UTC, emmiiorji approved these changes
Hi @Ofarouq310, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Red-approved](https://user-images.githubusercontent.com/20554583/199362837-208e4c72-b63b-4cdb-a8ed-cebfdac94960.gif)

## Good Highlights

- Linter checks are passing
- Adherence to GitHub flow
- Repo is professional
- Good commit messages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 22:51 UTC, merged

2022-11-07 07:41 UTC, rloterh reviewed
## Status: Approved :heavy_check_mark:

Hi Omar,  

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- Good job

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

**You can also consider:**
- I think you should change the header title _Authors_ to _Author_ in your ReadMe, as this project is worked on by a sole contributor. 
- MIT license link in your ReadMe is broken, kindly endeavor to fix it.
Implementing the above change(s) will make your ReadMe/ repository stand out even better 😉

keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._